db:
  url: jdbc:mysql://192.168.42.230:3306/shanxi-upms?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  username: root
  password: 123456
  driver: com.mysql.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://Nmghr:NMhr$123@192.168.43.32:7007/eureka/
log:
  level:error
pki:
  #认证地址
  authURL: http://127.0.0.1:6180/MessageService
  #应用标识，根据实际情况修改，与网关中的配置的应用标识一致
  appId: testApp
  #调用应用服务器或者网关生成原文标志 1:调用应用服务器 2:调用网关，默认为1
  randomFrom: 1
  #是否检查访问控制状态，当设置为"true"时，网关检查用户是否允许访问此应用，并在报文中给出相应的信息，默认为为false
  accessControl: false
  #是否开启二维码验证，默认false
  qRCodeAuth: false