db:
  url: jdbc:mysql://192.168.42.230:3306/shanxi-upms?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  username: root
  password: 123456
  driver: com.mysql.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://Nmghr:NMhr$123@192.168.43.32:7007/eureka/
log:
  level:error