management.security.enabled: false
spring.jmx.enabled: false

server:
  port: 8082
  servlet:
    contextPath: /upms
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8
  application:
    name: upms
  profiles:
    active: dev
  datasource:
    separator: ;;
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ${db.driver}
    platform: mysql
    initial-size: 2
    maximum-pool-size: 10
    connection-timeout: 5000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    continue-on-error: true
    initialization-mode: always
  mail:
    protocol: smtp
    host: smtp.163.com
    port: 465
    from: UPMS
    account: 123wangpengwei@163.com
    password: wangpengwei1987
    smtpAuth: true
    sslEnable: true
    charset: utf-8

eureka:
  client:
    registerWithEureka: false
    healthcheck:
      enabled: false # 开启健康检查
    fetchRegistry: false
    registry-fetch-interval-seconds: 60 #获取注册信息的时间间隔(S),默认为30秒
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10  #生产环境上，这个值得设为30
    lease-expiration-duration-in-seconds: 10   #生产环境上，这个值得设为30
user:
  defaultPwd: 12345678
  loginFailIntervalMinutes: 5
  loginFailInTimes: 3
  loginBanIntervalMinutes: 30
pki:
  #认证地址
  authURL: ${pki.authURL}
  #应用标识，根据实际情况修改，与网关中的配置的应用标识一致
  appId: ${pki.appId}
  #调用应用服务器或者网关生成原文标志 1:调用应用服务器 2:调用网关，默认为1
  randomFrom: ${pki.randomFrom}
  #是否检查访问控制状态，当设置为"true"时，网关检查用户是否允许访问此应用，并在报文中给出相应的信息，默认为为false
  accessControl: ${pki.accessControl}
  #是否开启二维码验证，默认false
  qRCodeAuth: ${pki.qRCodeAuth}
  